title: 보리꾸는 귀여워
# logo_img: /assets/img/icons/simplex_logo.svg
favicon: /assets/favicon.ico
description: 노력
global_tags: 개발일지
copyright: © JanghyeonJung 2024

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"